name: PR update

on:
  pull_request:
    types: [ labeled ]

jobs:
  update_pr:
    name: PR update
    if: ${{ github.event.label.name == 'Release PR checklist' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.base_ref }} == master || ${{ github.base_ref }} == dev || ${{ github.base_ref }} == next-release ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '[A-Za-z\d-_.\\/]+'
          title-template: 'Build: Release PR'
          body-template: |
            ### Description
            - Final release PR. Please check all the checklist below before merging.
            ---
            ### Checklist:
            - [ ] Check if astra-notice library is updated to latest
            - [ ] Check if Elementor & Elementor Pro compatibility tags are updated to latest
            - [ ] Update - Tested Upto - readme.txt
            - [ ] Update Readme.txt file and then run: `grunt readme`
            - [ ] Run to update version number  : `grunt version-bump --ver=<version-number>`
            - [ ] Generate POT file             : `grunt i18n`
            - [ ] PHPCS - vendor/bin/phpcs
            - [ ] Add draft a tag GitHub
            - [ ] Open PR to backport branch to `next-release`
            ---
          body-update-action: 'prefix'
          title-update-action: 'prefix'
          body-uppercase-base-match: false